# Generated by Django 2.0.4 on 2018-04-22 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saves', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='save',
            name='date',
        ),
    ]
