# Generated by Django 2.0.4 on 2018-04-22 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saves', '0003_save_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='save',
            options={'ordering': ['name'], 'verbose_name': 'Save', 'verbose_name_plural': 'Saves'},
        ),
    ]
