# Generated by Django 2.0.4 on 2018-04-26 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='save',
            new_name='fsave',
        ),
    ]
