# Generated by Django 2.0.4 on 2018-04-22 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0002_auto_20180422_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='save',
        ),
    ]
