# Generated by Django 2.0.4 on 2018-04-22 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saves', '0004_auto_20180423_0029'),
        ('incomes', '0003_remove_income_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='to_save',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='saves.Save'),
            preserve_default=False,
        ),
    ]
