# Generated by Django 2.0.3 on 2018-04-23 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0004_income_to_save'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='to_save',
            new_name='by_save',
        ),
    ]
