# Generated by Django 2.0.4 on 2018-04-22 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0002_auto_20180422_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outcome',
            old_name='save',
            new_name='ssave',
        ),
    ]
