# Generated by Django 2.0.4 on 2018-04-22 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saves', '0004_auto_20180423_0029'),
        ('outcomes', '0003_auto_20180422_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outcome',
            name='ssave',
        ),
        migrations.AddField(
            model_name='outcome',
            name='to_save',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='save', to='saves.Save'),
            preserve_default=False,
        ),
    ]
