# Generated by Django 2.0.4 on 2018-04-22 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0004_auto_20180423_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='to_save',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', related_query_name='save', to='saves.Save'),
        ),
    ]
