# Generated by Django 2.0.3 on 2018-04-23 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0005_auto_20180423_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outcome',
            old_name='to_save',
            new_name='by_save',
        ),
    ]
